#!/usr/bin/env python3
"""
Cleanup script to remove test files generated by the document writer/reader scripts.
"""

import os

current_dir = os.path.dirname(os.path.abspath(__file__))

files_to_remove = [
    "document_summary.txt",
    "document_bullets.txt"
]

for filename in files_to_remove:
    filepath = os.path.join(current_dir, filename)
    if os.path.exists(filepath):
        os.remove(filepath)
        print(f"Removed: {filepath}")
    else:
        print(f"Not found: {filepath}")

print("Cleanup complete!")